# GoReleaser configuration for spemu
# https://goreleaser.com

version: 1

project_name: spemu

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: spemu
    main: .
    binary: spemu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
    flags:
      - -trimpath

archives:
  - id: spemu
    builds:
      - spemu
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: nu0ma
    name: spemu
  draft: false
  prerelease: auto
  name_template: "Release {{ .Version }}"

brews:
  - name: spemu
    tap:
      owner: nu0ma
      name: spemu
    repository:
      owner: nu0ma
      name: spemu
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: nu0ma
          name: spemu
          branch: main
    directory: homebrew
    homepage: https://github.com/nu0ma/spemu
    description: "DML executor for Google Cloud Spanner Emulator"
    license: MIT
    test: |
      system "#{bin}/spemu --help"
    install: |
      bin.install "spemu"

dockers:
  - image_templates:
      - "ghcr.io/nu0ma/spemu:{{ .Version }}"
      - "ghcr.io/nu0ma/spemu:latest"
    dockerfile: Dockerfile
    extra_files:
      - README.md

announce:
  skip: true