services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    container_name: spemu-spanner-emulator
    ports:
      - "9010:9010"
      - "9020:9020"
    environment:
      - SPANNER_EMULATOR_HOST=localhost:9010

  # Service to initialize the database with built-in schema initialization
  spanner-init:
    image: golang:1.24-alpine
    platform: linux/amd64
    container_name: spemu-spanner-init
    depends_on:
      - spanner-emulator
    environment:
      - SPANNER_EMULATOR_HOST=spanner-emulator:9010
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        apk add --no-cache git netcat-openbsd &&
        go mod download &&
        echo 'Waiting for emulator to be ready...' &&
        timeout 60 sh -c 'until nc -z spanner-emulator 9010; do sleep 2; done' &&
        echo 'Initializing database with built-in schema support...' &&
        go run . --project test-project --instance test-instance --database test-database --init-schema test/schema.sql --verbose &&
        echo 'Database setup complete!'
      "
    profiles:
      - init

