services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    container_name: spemu-spanner-emulator
    ports:
      - "9010:9010"
      - "9020:9020"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9020/"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    environment:
      - SPANNER_EMULATOR_HOST=localhost:9010

  # Optional: Service to initialize the database
  spanner-init:
    image: golang:1.24-alpine
    platform: linux/amd64
    container_name: spemu-spanner-init
    depends_on:
      spanner-emulator:
        condition: service_healthy
    environment:
      - SPANNER_EMULATOR_HOST=spanner-emulator:9010
    volumes:
      - ./test:/workspace/test
      - ./scripts:/workspace/scripts
      - ./go.mod:/workspace/go.mod
      - ./go.sum:/workspace/go.sum
    working_dir: /workspace
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        apk add --no-cache git &&
        go mod download &&
        echo 'Waiting for emulator to be ready...' &&
        sleep 5 &&
        echo 'Running setup script...' &&
        go run scripts/setup.go &&
        echo 'Database setup complete!'
      "
    profiles:
      - init

  # Development service for running tests
  spemu-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spemu-dev
    depends_on:
      spanner-emulator:
        condition: service_healthy
    environment:
      - SPANNER_EMULATOR_HOST=spanner-emulator:9010
      - CGO_ENABLED=0
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /workspace
    command: tail -f /dev/null
    profiles:
      - dev

volumes:
  go-mod-cache:
  go-build-cache: