services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    container_name: spemu-spanner-emulator
    ports:
      - "9010:9010"
      - "9020:9020"
    environment:
      - SPANNER_EMULATOR_HOST=localhost:9010

  # Optional: Service to initialize the database
  spanner-init:
    image: golang:1.24-alpine
    platform: linux/amd64
    container_name: spemu-spanner-init
    depends_on:
      - spanner-emulator
    environment:
      - SPANNER_EMULATOR_HOST=spanner-emulator:9010
    volumes:
      - ./test:/workspace/test
      - ./scripts:/workspace/scripts
      - ./go.mod:/workspace/go.mod
      - ./go.sum:/workspace/go.sum
    working_dir: /workspace
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        apk add --no-cache git &&
        go mod download &&
        echo 'Waiting for emulator to be ready...' &&
        sleep 5 &&
        echo 'Running setup script...' &&
        go run scripts/setup.go &&
        echo 'Database setup complete!'
      "
    profiles:
      - init

